apiVersion: v1
kind: Service
metadata:
  name: instaforge
  namespace: instaforge
  labels:
    app: instaforge
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: instaforge
---
apiVersion: v1
kind: Service
metadata:
  name: instaforge-metrics
  namespace: instaforge
  labels:
    app: instaforge
    type: metrics
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics
    protocol: TCP
  selector:
    app: instaforge
